export enum LocalStorageEnum {
  ACCESS_TOKEN = 'MASSCHECK_ACCESS_TOKEN',
  REFRESH_TOKEN = 'MASSCHECK_REFRESH_TOKEN',
  EXPIRE_TIME_TOKEN = 'MASSCHECK_EXPIRE_TIME_TOKEN',
  EXT_MASSCHECK_INTERFACE_STATE = 'MASSCHECK_EXT_MASSCHECK_INTERFACE_STATE',
}
