export enum LocalStorageEnum {
  ACCESS_TOKEN = 'MASSCHECK_ACCESS_TOKEN',
  REFRESH_TOKEN = 'MASSCHECK_REFRESH_TOKEN',
  EXPIRE_TIME_TOKEN = 'MASSCHECK_EXPIRE_TIME_TOKEN',
  DISPLAY_NAME = 'MASSCHECK_DISPLAY_NAME',
  XPX_ADDRESS = 'MASSCHECK_XPX_ADDRESS',
  EXT_IS_ACTIVATE = 'MASSCHECK_EXT_IS_ACTIVATE',
  UID = 'MASSCHECK_UID',
}
