export enum LocalStorageEnum {
  DISPLAY_NAME = 'DISPLAY_NAME',
  UID = 'UID',
  ADDRESS = 'ADDRESS',
  IS_NEW_USER = 'IS_NEW_USER',
  IS_FIRST_COUNTDOWN = 'IS_FIRST_COUNTDOWN',
  IS_SIGN_IN = 'IS_SIGN_IN',
  STAGE = 'STAGE',
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  EXPIRE_TIME_TOKEN = 'EXPIRE_TIME_TOKEN'
}
